<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=9" >

<title>Create a table to join the Waterbody IDs (WBID) for lakes in MRB1 (HUC01 and HUC02) from NHDplus Version 1 and 2</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>




</head>

<body>
<h1>Create a table to join the Waterbody IDs (WBID) for lakes in MRB1 (HUC01 and HUC02) from NHDplus Version 1 and 2</h1>

<!---
use these command instead of the knit icon if you want the data and work loaded into the R workspace
  library(knitr)
  knit('./tables/joinMRB1_V1V2.rmd')
-->

<h2>Introduction:</h2>

<ul>
<li>We have two versions of the lakes of MRB1 (Major River Basin 1: HUC regions 01 and 02) from NHDplus.<br/></li>
<li>Need to compare the two version to see if the WB_IDs (unique identifiers), lake locations, and areas match.<br/></li>
<li>The output is a table (joinMRB1_V1B2) that crosswalks the WB_IDs from one version to the other.</li>
<li>This document shows the details of the data comparisons and the creation of the join table.</li>
</ul>

<hr/>

<p>The following code will open the formatted text version of the Rmarkdown file in a browser:</p>

<hr/>

<pre><code>browseURL(&#39;https://github.com/willbmisled/LakesDB/blob/master/tables/joinMRB1_V1V2.md&#39;)
</code></pre>

<hr/>

<p>The data can be loaded into R with the following code:</p>

<hr/>

<p>#Get the Data
    load(url(&#39;<a href="https://raw.github.com/willbmisled/LakesDB/master/tables/joinMRB1_V1V2.rda&#x27;">https://raw.github.com/willbmisled/LakesDB/master/tables/joinMRB1_V1V2.rda&#39;</a>)</p>

<h2>Data Definitions </h2>

<p>joinMRB1_V1V2 is a data frame with 28136 obs. and 4 variables</p>

<p><strong>joinMRB1_V1V2 Data Definitions:</strong></p>

<table><thead>
<tr>
<th><strong>Field</strong></th>
<th><strong>Definition</strong></th>
</tr>
</thead><tbody>
<tr>
<td><strong>WBID_V1</strong></td>
<td>Waterbody ID for NHDplus V1 lakes; same as V1$WB_ID</td>
</tr>
<tr>
<td><strong>WBID_V2</strong></td>
<td>Waterbody ID for NHDplus V2 lakes; same as V1$COMID</td>
</tr>
<tr>
<td><strong>flag</strong></td>
<td>Indicates that the there may be differences in how V1 and V2 represent the lake (see below)</td>
</tr>
<tr>
<td><strong>comment</strong></td>
<td>additional information on the lake or the flag</td>
</tr>
</tbody></table>

<p><strong>joinMRB1_V1V2 flag Definitions:</strong></p>

<table><thead>
<tr>
<th><strong>Flag</strong></th>
<th><strong>Definition</strong></th>
</tr>
</thead><tbody>
<tr>
<td>flag==0</td>
<td>Lakes Colocated with equal areas; Note: WBIDs may be the same or different in V1 and V2</td>
</tr>
<tr>
<td>flag==1</td>
<td>Single Lake in V1 split into two or more lakes in V2</td>
</tr>
<tr>
<td>flag==2</td>
<td>Multiple Lakes in V1 represented as a single lake in V2</td>
</tr>
<tr>
<td>flag==3</td>
<td>Lakes collocated but areas unequal</td>
</tr>
<tr>
<td>flag==4</td>
<td>In V1 but not V2</td>
</tr>
<tr>
<td>flag==5</td>
<td>In V2 but not V1</td>
</tr>
<tr>
<td>flag==6</td>
<td>V2 Duplicate lake; V2_166421080=V2_19333669=V1_19333669</td>
</tr>
</tbody></table>

<h2>Data</h2>

<ul>
<li> Load the NHD HUC01 &amp; 02 lakes (MRB1) based on NHDplus Version 1. </li>
<li> Reproject to Albers</li>
<li> Associate lake holes with correct polygon</li>
<li> Save as SpatialPolygonsDataFrame &ldquo;V1&rdquo;</li>
</ul>

<p>Here are the first few lines of the V1 attribute data: </p>

<pre><code>##   OBJECTID WB_ID AlbersAreaM Centroid_Long Centroid_Lat ShorelineAlbersM
## 1        1   487       42396        -68.38        46.19            896.8
## 2        2   489       26178        -68.39        46.19            735.7
## 3        3   491     1480297        -68.38        46.18           7741.6
## 4        4   493       67348        -68.11        46.19           1056.2
## 5        5   495       68737        -68.42        46.18           1671.7
## 6        6   499       27255        -68.36        46.18            700.0
##   Shape_Length  Shape_Area AlbersX AlbersY HUC_Region
## 1     0.009059 0.000004941 2106441 1279649          1
## 2     0.008068 0.000003051 2105817 1279255          1
## 3     0.084338 0.000172488 2106786 1278696          1
## 4     0.011058 0.000007848 2126595 1285107          1
## 5     0.019320 0.000008010 2104045 1278093          1
## 6     0.008649 0.000003176 2108146 1278936          1
</code></pre>

<p><strong>Note:</strong>  for V1 the only important attribute (for now) is the WB_ID.  This is the unique id for the lake</p>

<ul>
<li> Load the NHD HUC01 lakes based on NHDplus Version 2.</li>
<li> Load the NHD HUC02 lakes based on NHDplus Version 2.</li>
<li> Combine HUC01 and HUC02</li>
<li> Associate lake holes with correct polygon</li>
<li> Save as SpatialPolygonsDataFrame &ldquo;V2&rdquo;</li>
</ul>

<p>Here are the first few lines of the V2 attribute data: </p>

<pre><code>##             COMID
## 10101972 10101972
## 10101978 10101978
## 10101982 10101982
## 10101984 10101984
## 10101986 10101986
## 10101990 10101990
</code></pre>

<p><strong>Note:</strong>  for V2 the only attribute is the COMID.  This is the unique id for the lake and should match V1$WB_ID</p>

<h2>Compare V1 and V2</h2>

<p>WBID is the unique ID for the Waterbody.  This was derived from the NHDplus COMID.  The lakes files use different naming conventions in V1 the WBID is V1$WB_ID.  For V2 it is V2$COMID.  Both files are in the Albers projection.</p>

<p>Comparison Steps:
<br></p>

<ul>
<li>calculate lake areas for V1 and V2</li>
<li>merge the WBIDs and Areas for V1 and V2</li>
<li>lakes with whose WBID and Area match are considered to be the same lake.<br/></li>
<li>A dataframe (joinMRB1_V1V2) is created with the matching that maps the WBIDs for V1 to those in V2.</li>
<li>The &ldquo;over&rdquo; function from the &ldquo;sp&rdquo; package used to spatially join the lakes in V1 that are not matched in V2 (and vice versa).</li>
<li>This provides a list of potential V1/V2 WBID matches</li>
<li>area is merged to this list and lakes whose areas and locations match are considered to be the same lake with different WBIDs.  These WBIDs are added to joinMRB1_V1V2</li>
<li>This leaves a data.frame (chkV1V2) with information on lakes that need to be checked graphically.</li>
<li>The list includes:

<ol>
<li>Lakes in one Version that do not overlay lakes in the other version.  These could be lakes that were undetected in one version or were determined not to be lakes.</li>
<li>Lakes whose positions overlap but the areas don&#39;t match.  In most cases one version of NHDplus divided the lakes differently than the other version (i.e. V1 shows 1 lake while V2 shows 2 lakes)
*The lakes listed in chkV1V2 were used to create the SpatialPolygonsDataFrame &ldquo;chkLakes&rdquo;.  This was reprojected to WGS84 to match googlemaps</li>
</ol></li>
</ul>

<p><br> 
<strong>These are the lakes that need to be verified:</strong></p>

<pre><code>##     WBID_V1   WBID_V2 nV1 nV2 flagWBID   areaV1   areaV2 perDif flagArea
## 1   1720193   1720187   2   1        1  1409433  1243674   0.12        1
## 2   1720193   1720193   2   1        1  1409433   165757   0.88        1
## 3   9312497   5842312   2   1        1  3939308  3015457   0.23        1
## 4   9312497 120053397   2   1        1  3939308   898004   0.77        1
## 5   9326606   9326590   2   1        1  4655489  1151119   0.75        1
## 6   9326606   9326606   2   1        1  4655489  3504371   0.25        1
## 7   9479066   9443357   2   1        1    90662    82919   0.09        1
## 8   9479066   9479066   2   1        1    90662     7742   0.91        1
## 9   9512548   9512546   2   1        1  9198135  9072954   0.01        1
## 10  9512548   9512548   2   1        1  9198135   125180   0.99        1
## 11 11686920   4724203   3   1        1 75539790    16735   1.00        1
## 12 11686920   4726045   3   1        1 75539790 46468664   0.38        1
## 13 11686920 120053255   3   1        1 75539790 29054387   0.62        1
## 14 22222791   7688829   2   1        1  2367407  2305872   0.03        1
## 15 22222791  22222791   2   1        1  2367407  2305872   0.03        1
## 16 22223101   7689297   3   1        1    49256     8773   0.82        1
## 17 22223101   9344247   3   1        1    49256    14948   0.70        1
## 18 22223101 166174657   3   1        1    49256    25534   0.48        1
## 19  7717818 120052268   1   2        1  6542258 10364202   0.58        1
## 20  7717850 120052268   1   2        1  3821949 10364202   1.71        1
## 21  8086079 120053438   1   2        1    21356    34158   0.60        1
## 22 22746261 120053438   1   2        1    12801    34158   1.67        1
## 23  6094729 166174730   1   1        0    11963  5123479 427.28        1
## 24  6710763 931050002   1   1        0     9314   375329  39.30        1
## 25  6732123 166174267   1   1        0   169247 15832932  92.55        1
## 26  6760548 931070002   1   1        0    24786 15283308 615.61        1
## 27  8390908   8390908   1   1        0   338542   112019   0.67        1
## 28       NA  15516920  NA   1        2       NA    14580     NA        2
## 29       NA  15516922  NA   1        2       NA    14710     NA        2
## 30       NA  60444415  NA   1        2       NA    58649     NA        2
## 31       NA 166421080  NA   1        2       NA 97407208     NA        2
## 32  4782861        NA   1  NA        2 15023566       NA     NA        2
## 33 10312598        NA   1  NA        2  4707417       NA     NA        2
## 34 22287527        NA   1  NA        2   717449       NA     NA        2
## 35 22287665        NA   1  NA        2    67309       NA     NA        2
</code></pre>

<p><br> </p>

<h2>Visually check the flagged lakes with colocated matches:</h2>

<ul>
<li>ChkV1V2 sorted by WBID_V1 and WBID_V2</li>
<li>From the list choose the row numbers of lakes that appear as a single lake in one version and multiple lakes in another and plot them.</li>
<li>lakes plotted first by version then as an overlay on a google map.</li>
<li>Visually check the plots and decide how to resolve the differences</li>
<li><p>Update joinMRB1_V1V2</p></li>
<li><p>For <strong>chkV1V2[c(1, 2),]</strong> </p>

<ul>
<li>WBID_v1=c(1720193)</li>
<li>WBID_v2=c(1720187, 1720193)<br/></li>
</ul></li>
<li><p>Plotting the lakes (see below) indicates they are contiguous and could be joined or separate.</p></li>
<li><p>Add WBIDs to joinMRB1_V1V2 with flag=1 indicating a single lake in V1 maps to multiple lake in V2</p></li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=45.418623,-69.298091&amp;zoom=14&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows1_21.png" alt="plot of chunk Rows1,2"/> <img src="figure/Rows1_22.png" alt="plot of chunk Rows1,2"/> <img src="figure/Rows1_23.png" alt="plot of chunk Rows1,2"/> </p>

<ul>
<li>For <strong>chkV1V2[c(3, 4),]</strong> 

<ul>
<li>WBID_v1=c(9312497)</li>
<li>WBID_v2=c(5842312, 120053397)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates they are contiguous and could be joined or separate.</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=1 indicating a single lake in V1 maps to multiple lake in V2</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.522295,-70.862386&amp;zoom=13&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows3_41.png" alt="plot of chunk Rows3,4"/> <img src="figure/Rows3_42.png" alt="plot of chunk Rows3,4"/> <img src="figure/Rows3_43.png" alt="plot of chunk Rows3,4"/> </p>

<ul>
<li>For <strong>chkV1V2[c(5, 6),]</strong> 

<ul>
<li>WBID_v1=c(9326606)</li>
<li>WBID_v2=c(9326590, 9326606)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates they are contiguous and could be joined or separate.</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=1 indicating a single lake in V1 maps to multiple lake in V2</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.627879,-72.151526&amp;zoom=13&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows5_61.png" alt="plot of chunk Rows5,6"/> <img src="figure/Rows5_62.png" alt="plot of chunk Rows5,6"/> <img src="figure/Rows5_63.png" alt="plot of chunk Rows5,6"/> </p>

<ul>
<li>For <strong>chkV1V2[c(7, 8),]</strong> 

<ul>
<li>WBID_v1=c(9479066)</li>
<li>WBID_v2=c(9443357, 9479066)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates they are contiguous and could be joined or separate.</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=1 indicating a single lake in V1 maps to multiple lake in V2</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=39.559788,-74.393368&amp;zoom=16&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows7_81.png" alt="plot of chunk Rows7,8"/> <img src="figure/Rows7_82.png" alt="plot of chunk Rows7,8"/> <img src="figure/Rows7_83.png" alt="plot of chunk Rows7,8"/> </p>

<ul>
<li>For <strong>chkV1V2[c(9, 10),]</strong> 

<ul>
<li>WBID_v1=c(9512548)</li>
<li>WBID_v2=c(9512546, 9512548)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates they are contiguous and could be joined or separate.</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=1 indicating a single lake in V1 maps to multiple lake in V2</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=40.616363,-74.828838&amp;zoom=13&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows9_101.png" alt="plot of chunk Rows9,10"/> <img src="figure/Rows9_102.png" alt="plot of chunk Rows9,10"/> <img src="figure/Rows9_103.png" alt="plot of chunk Rows9,10"/> </p>

<ul>
<li>For <strong>chkV1V2[c(11, 12, 13),]</strong> 

<ul>
<li>WBID_v1=c(11686920)</li>
<li>WBID_v2=c(4724203, 4726045, 120053255)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates they are contiguous and could be joined or separate.</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=1 indicating a single lake in V1 maps to multiple lake in V2</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=39.845476,-76.350141&amp;zoom=10&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows11:131.png" alt="plot of chunk Rows11:13"/> <img src="figure/Rows11:132.png" alt="plot of chunk Rows11:13"/> <img src="figure/Rows11:133.png" alt="plot of chunk Rows11:13"/> </p>

<ul>
<li>For <strong>chkV1V2[c(14, 15),]</strong> 

<ul>
<li>WBID_v1=c(22222791)</li>
<li>WBID_v2=c(7688829, 22222791)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates they are contiguous and could be joined or separate.</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=1 indicating a single lake in V1 maps to multiple lake in V2</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=42.410645,-72.22527&amp;zoom=14&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows14_151.png" alt="plot of chunk Rows14,15"/> <img src="figure/Rows14_152.png" alt="plot of chunk Rows14,15"/> <img src="figure/Rows14_153.png" alt="plot of chunk Rows14,15"/> </p>

<ul>
<li>For <strong>chkV1V2[c(16, 17, 18),]</strong> 

<ul>
<li>WBID_v1=c(22223101)</li>
<li>WBID_v2=c(7689297, 9344247, 166174657)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates they are contiguous and could be joined or separate.</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=1 indicating a single lake in V1 maps to multiple lake in V2</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=42.212832,-71.999227&amp;zoom=16&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows16:181.png" alt="plot of chunk Rows16:18"/> <img src="figure/Rows16:182.png" alt="plot of chunk Rows16:18"/> <img src="figure/Rows16:183.png" alt="plot of chunk Rows16:18"/> </p>

<ul>
<li>For <strong>chkV1V2[c(19, 20),]</strong> 

<ul>
<li>WBID_v1=c(7717818, 7717850)</li>
<li>WBID_v2=c(120052268)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates they are contiguous and could be joined or separate.</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=2 indicating multiple lakes in V1 map to a single lake in V2</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=41.461673,-73.289158&amp;zoom=11&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows19:201.png" alt="plot of chunk Rows19:20"/> <img src="figure/Rows19:202.png" alt="plot of chunk Rows19:20"/> <img src="figure/Rows19:203.png" alt="plot of chunk Rows19:20"/> </p>

<ul>
<li>For <strong>chkV1V2[c(21, 22),]</strong> 

<ul>
<li>WBID_v1=c(8086079, 22746261)</li>
<li>WBID_v2=c(120053438)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates they are contiguous and could be joined or separate.</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=2 indicating multiple lakes in V1 map to a single lake in V2</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=42.499641,-75.15594&amp;zoom=17&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows21:221.png" alt="plot of chunk Rows21:22"/> <img src="figure/Rows21:222.png" alt="plot of chunk Rows21:22"/> <img src="figure/Rows21:223.png" alt="plot of chunk Rows21:22"/> </p>

<ul>
<li>For <strong>chkV1V2[c(23),]</strong> 

<ul>
<li>WBID_v1=c(6094729)</li>
<li>WBID_v2=c(166174730)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates that V1 and V2 have different views of this lake.</li>
<li>From the googlemap image it looks like it isn&#39;t really a lake or a small one.</li>
<li>The V2 lake (WBID==166174730) is much larger than the V1 lake (WBID=6094729)</li>
<li>When plotted together it is clear that the V1 lake is a tiny spot on the south end of V2</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=3 and the comment: Lakes collocated but areas unequal</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=42.327423,-72.856455&amp;zoom=12&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows231.png" alt="plot of chunk Rows23"/> <img src="figure/Rows232.png" alt="plot of chunk Rows23"/> <img src="figure/Rows233.png" alt="plot of chunk Rows23"/> </p>

<p><img src="figure/Rows23a.png" alt="plot of chunk Rows23a"/> </p>

<ul>
<li>For <strong>chkV1V2[c(24),]</strong> 

<ul>
<li>WBID_v1=c(6710763)</li>
<li>WBID_v2=c(931050002)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates that V1 and V2 have different views of this lake.</li>
<li>From the googlemap image it looks like the V2 is a much better representation of the lake.</li>
<li>The V2 lake (WBID==931050002) is much larger than the V1 lake (WBID=6710763)</li>
<li>When plotted together it is clear that the V1 lake is a portion of V2</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=3 and the comment: Lakes collocated but areas unequal</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=44.254117,-69.531488&amp;zoom=16&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows241.png" alt="plot of chunk Rows24"/> <img src="figure/Rows242.png" alt="plot of chunk Rows24"/> <img src="figure/Rows243.png" alt="plot of chunk Rows24"/> </p>

<p><img src="figure/Rows24a.png" alt="plot of chunk Rows24a"/> </p>

<ul>
<li>For <strong>chkV1V2[c(25),]</strong> 

<ul>
<li>WBID_v1=c(6732123)</li>
<li>WBID_v2=c(166174267)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates that V1 and V2 have different views of this lake.</li>
<li>From the googlemap image it looks like the V2 is a much better representation of the lake.</li>
<li>The V2 lake (WBID==166174267) is much larger than the V1 lake (WBID=6732123)</li>
<li>When plotted together it is clear that the V1 lake is a portion of V2</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=3 and the comment: Lakes collocated but areas unequal</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.517782,-71.689855&amp;zoom=12&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows251.png" alt="plot of chunk Rows25"/> <img src="figure/Rows252.png" alt="plot of chunk Rows25"/> <img src="figure/Rows253.png" alt="plot of chunk Rows25"/> </p>

<p><img src="figure/Rows25a.png" alt="plot of chunk Rows25a"/> </p>

<ul>
<li>For <strong>chkV1V2[c(26),]</strong> 

<ul>
<li>WBID_v1=c(6760548)</li>
<li>WBID_v2=c(931070002)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates that V1 and V2 have different views of this lake.</li>
<li>From the googlemap image it looks like the V2 is a much better representation of the lake.</li>
<li>The V2 lake (WBID==931070002) is much larger than the V1 lake (WBID=6760548)</li>
<li>When plotted together it is clear that the V1 lake is a portion of V2</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=3 and the comment: Lakes collocated but areas unequal</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.35065,-71.757673&amp;zoom=12&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows261.png" alt="plot of chunk Rows26"/> <img src="figure/Rows262.png" alt="plot of chunk Rows26"/> <img src="figure/Rows263.png" alt="plot of chunk Rows26"/> </p>

<p><img src="figure/Rows26a.png" alt="plot of chunk Rows26a"/> </p>

<ul>
<li>For <strong>chkV1V2[c(27),]</strong> 

<ul>
<li>WBID_v1=c(8390908)</li>
<li>WBID_v2=c(8390908)</li>
</ul></li>
<li>Plotting the lakes (see below) indicates that V1 and V2 have different views of this lake.</li>
<li>From the googlemap image it looks like the V2 is a much better representation of the lake.</li>
<li>The V2 lake (WBID==8390908) is much larger than the V1 lake (WBID=8390908)</li>
<li>When plotted together it is clear that the V1 lake is a portion of V2</li>
<li>Add WBIDs to joinMRB1_V1V2 with flag=3 and the comment: Lakes collocated but areas unequal</li>
</ul>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=38.558567,-75.557132&amp;zoom=16&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
## Regions defined for each Polygons
</code></pre>

<p><img src="figure/Rows271.png" alt="plot of chunk Rows27"/> <img src="figure/Rows272.png" alt="plot of chunk Rows27"/> <img src="figure/Rows273.png" alt="plot of chunk Rows27"/> </p>

<p><img src="figure/Rows27a.png" alt="plot of chunk Rows27a"/> </p>

<p><img src="figure/27b.png" alt="plot of chunk 27b"/> </p>

<p><br> </p>

<h2>Visually check the lakes without matches in the other version</h2>

<ul>
<li>Four lakes present in V1 not present in V2</li>
<li>Four lakes present in V2 not present in V1</li>
</ul>

<pre><code>##     WBID_V1   WBID_V2 nV1 nV2 flagWBID   areaV1   areaV2 perDif flagArea
## 28       NA  15516920  NA   1        2       NA    14580     NA        2
## 29       NA  15516922  NA   1        2       NA    14710     NA        2
## 30       NA  60444415  NA   1        2       NA    58649     NA        2
## 31       NA 166421080  NA   1        2       NA 97407208     NA        2
## 32  4782861        NA   1  NA        2 15023566       NA     NA        2
## 33 10312598        NA   1  NA        2  4707417       NA     NA        2
## 34 22287527        NA   1  NA        2   717449       NA     NA        2
## 35 22287665        NA   1  NA        2    67309       NA     NA        2
##    flag
## 28    1
## 29    1
## 30    1
## 31    1
## 32    1
## 33    1
## 34    1
## 35    1
</code></pre>

<ul>
<li>Plot lake of interest</li>
<li>Adjust xlim and ylim to an area around the lake</li>
<li>Plot lakes for the other Version that are in the same vicinity</li>
<li>Plot lake on google map to see what it looks like</li>
<li>View plots and resolve the differences.</li>
<li>Update joinMRB1_V1V2</li>
</ul>

<h2>The missing lakes-6 of 8</h2>

<ul>
<li>Six of the eight lakes are easily resolved.<br/></li>
<li>They just aren&#39;t represented in the other version</li>
<li>These are shown in the plots</li>
</ul>

<p><img src="figure/a1.png" alt="plot of chunk a1"/> </p>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=40.155236,-76.750285&amp;zoom=12&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
</code></pre>

<p><img src="figure/a2.png" alt="plot of chunk a2"/> </p>

<pre><code class="r">Row &lt;- nrow(joinMRB1_V1V2) + 1  #row to add
joinMRB1_V1V2[Row, &quot;WBID_V1&quot;] &lt;- 4782861
joinMRB1_V1V2[Row, &quot;flag&quot;] &lt;- 4
joinMRB1_V1V2[Row, &quot;comment&quot;] &lt;- &quot;In V1 but not V2.&quot;
</code></pre>

<p><img src="figure/c1.png" alt="plot of chunk c1"/> </p>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.118195,-72.28975&amp;zoom=14&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
</code></pre>

<p><img src="figure/c2.png" alt="plot of chunk c2"/> </p>

<pre><code class="r">Row &lt;- nrow(joinMRB1_V1V2) + 1  #row to add
joinMRB1_V1V2[Row, &quot;WBID_V1&quot;] &lt;- 22287527
joinMRB1_V1V2[Row, &quot;flag&quot;] &lt;- 4
joinMRB1_V1V2[Row, &quot;comment&quot;] &lt;- &quot;In V1 but not V2.&quot;
</code></pre>

<p><img src="figure/d1.png" alt="plot of chunk d1"/> </p>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.304796,-73.681789&amp;zoom=16&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
</code></pre>

<p><img src="figure/d2.png" alt="plot of chunk d2"/> </p>

<pre><code class="r">Row &lt;- nrow(joinMRB1_V1V2) + 1  #row to add
joinMRB1_V1V2[Row, &quot;WBID_V1&quot;] &lt;- 22287665
joinMRB1_V1V2[Row, &quot;flag&quot;] &lt;- 4
joinMRB1_V1V2[Row, &quot;comment&quot;] &lt;- &quot;In V1 but not V2.&quot;
</code></pre>

<pre><code>## Error: missing value where TRUE/FALSE needed
</code></pre>

<pre><code>## Error: missing value where TRUE/FALSE needed
</code></pre>

<pre><code class="r">Row &lt;- nrow(joinMRB1_V1V2) + 1  #row to add  
joinMRB1_V1V2[Row, &quot;WBID_V2&quot;] &lt;- 15516920
joinMRB1_V1V2[Row, &quot;flag&quot;] &lt;- 5
joinMRB1_V1V2[Row, &quot;comment&quot;] &lt;- &quot;In V2 but not V1.&quot;
</code></pre>

<p><img src="figure/f1.png" alt="plot of chunk f1"/> </p>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.457838,-75.345451&amp;zoom=16&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
</code></pre>

<p><img src="figure/f2.png" alt="plot of chunk f2"/> </p>

<pre><code class="r">Row &lt;- nrow(joinMRB1_V1V2) + 1  #row to add  
joinMRB1_V1V2[Row, &quot;WBID_V2&quot;] &lt;- 15516922
joinMRB1_V1V2[Row, &quot;flag&quot;] &lt;- 5
joinMRB1_V1V2[Row, &quot;comment&quot;] &lt;- &quot;In V2 but not V1.&quot;
</code></pre>

<p><img src="figure/g1.png" alt="plot of chunk g1"/> </p>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=41.327801,-74.189293&amp;zoom=15&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
</code></pre>

<p><img src="figure/g2.png" alt="plot of chunk g2"/> </p>

<pre><code class="r">Row &lt;- nrow(joinMRB1_V1V2) + 1  #row to add  
joinMRB1_V1V2[Row, &quot;WBID_V2&quot;] &lt;- 60444415
joinMRB1_V1V2[Row, &quot;flag&quot;] &lt;- 5
joinMRB1_V1V2[Row, &quot;comment&quot;] &lt;- &quot;In V2 but not V1.&quot;
</code></pre>

<h2>The missing lakes-the penultimate</h2>

<ul>
<li>V1_WBID=10312598 is the southern edge of Lake Champlain (V1 and V2 WBID=22302965)</li>
<li>In the Waterbody database V1_WBID=10312598 is separate from V1_WBID=22302965 </li>
<li>When the overlay was done above V1_WBID=22302965 was matched to V2_WBID=22302965</li>
<li>The match between V1 and V2 WBID=22302965 joinMRB1_V1V2 was flagged and commented</li>
<li>A new entry in joinMRB1_V1V2 showing the link between V1_WBID=10312598 and V2_WBID=22302965 was added.</li>
<li>Here are the graphics for V1_WBID=10312598:</li>
</ul>

<p><img src="figure/b1.png" alt="plot of chunk b1"/> </p>

<pre><code>## Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=43.558438,-73.455178&amp;zoom=10&amp;size=%20640x640&amp;scale=%202&amp;maptype=satellite&amp;sensor=false
## Google Maps API Terms of Service : http://developers.google.com/maps/terms
</code></pre>

<p><img src="figure/b2.png" alt="plot of chunk b2"/> </p>

<pre><code>## Error: missing values are not allowed in subscripted assignments of data
## frames
</code></pre>

<pre><code>## Error: missing values are not allowed in subscripted assignments of data
## frames
</code></pre>

<h2>The missing lakes-the ultimate</h2>

<ul>
<li>The overlay did not find a match for V2_WBID=166421080 in V1</li>
<li><p>When V2_WBID=166421080 and  V1 lakes are plotted V2_WBID=166421080 is seen to be colocated with a V1 lakes
<img src="figure/h1.png" alt="plot of chunk h1"/> </p></li>
<li><p>When he HUC01 shapefile is opened in ArcMap there is no lake corresponding to  V2_WBID=166421080 in the attribute table.</p></li>
<li><p>V2_WBID=19333669,however, is in the same location.</p></li>
<li><p>Returning to R V2_WBID=19333669 and V2_WBID=166421080 are plotted and are clearly the same lake; in the same location and the areas match.</p></li>
<li><p>So this is what is happening.  Lake V2_WBID=166421080 and V2_WBID=19333669 are the same lake and one should be deleted.</p></li>
<li><p>V2_WBID=19333669 is also the same as V1_WBID=19333669</p></li>
<li><p>Need to update joinMRB1_V1V2 to reflect this adding a new flag code #5 to explain what happened.</p></li>
</ul>

<p><img src="figure/h2.png" alt="plot of chunk h2"/> </p>

<pre><code>##        WBID_V1  WBID_V2 flag
## 26380 19333669 19333669    0
##                                                comment
## 26380 Same Lake; WBID_V1==WBID_V2 and lake areas match
</code></pre>

<h2>QAQC-Check to make sure all V1 and V2 WBIDs are included in joinMRB1_V1V2</h2>

<ul>
<li>All V1 and V2 WBIDs are in joinMRB1_V1V2</li>
</ul>

<pre><code class="r">table(V1$WB_ID %in% joinMRB1_V1V2$WBID_V1)
</code></pre>

<pre><code>## 
##  TRUE 
## 28122
</code></pre>

<pre><code class="r">table(V2$COMID %in% joinMRB1_V1V2$WBID_V2)
</code></pre>

<pre><code>## 
##  TRUE 
## 28130
</code></pre>

<ul>
<li>Checking if all joinMRB1_V1V2 WBIDs are in V1 and V2 shows that for each Version 3 are missing</li>
<li>For each version 3 lakes are found in one version and not the next so the mis-matches are NAs.</li>
</ul>

<pre><code class="r">table(joinMRB1_V1V2$WBID_V1 %in% V1$WB_ID)
</code></pre>

<pre><code>## 
## FALSE  TRUE 
##     3 28133
</code></pre>

<pre><code class="r">joinMRB1_V1V2[which(joinMRB1_V1V2$WBID_V1 %in% V1$WB_ID == FALSE), ]
</code></pre>

<pre><code>##       WBID_V1  WBID_V2 flag           comment
## 28132      NA 15516920    5 In V2 but not V1.
## 28133      NA 15516922    5 In V2 but not V1.
## 28134      NA 60444415    5 In V2 but not V1.
</code></pre>

<pre><code class="r">table(joinMRB1_V1V2$WBID_V2 %in% V2$COMID)
</code></pre>

<pre><code>## 
## FALSE  TRUE 
##     3 28133
</code></pre>

<pre><code class="r">joinMRB1_V1V2[which(joinMRB1_V1V2$WBID_V2 %in% V2$COMID == FALSE), ]
</code></pre>

<pre><code>##        WBID_V1 WBID_V2 flag           comment
## 28129  4782861      NA    4 In V1 but not V2.
## 28130 22287527      NA    4 In V1 but not V2.
## 28131 22287665      NA    4 In V1 but not V2.
</code></pre>

<h2>Save the data</h2>

<ul>
<li>joinMRB1_V1V2 save to &#39;./tables/joinMRB1_V1V2.rda&#39;</li>
</ul>

</body>

</html>

